### PR TITLE
Adding filter to $this->default_post_types

### PR DESCRIPTION
**Pull request by ryanwelcher**
Adding a filter to allow other post types to be used

### CODE REVIEW

**Comment by mjangda** [comment]
Since the root issue is that the `default_post_types` property doesn't updated when additional post_types are added/removed from zoninator, we should fix that instead. Otherwise, we make adding post_type support even harder (you have to call `add_post_type_support` AND filter this AND ...).

**Comment by mjangda** [comment]
Admittedly, this filter makes it pretty easy to add post type support but goes against the typical WordPress-way of adding post_type support. I think I'll need to think on it or additional feedback/viewpoints :)

**Comment by bcampeau** [comment]
:+1: to @mjangda I agree on that

**Comment by ryanwelcher** [comment]
Thanks for your feedback! I have taken a different approach based on your comment and issued a new pull request on a different branch - #34

**Comment by GaryJones** [comment]
Fixed with https://github.com/Automattic/zoninator/pull/73.

**Pull request closed without merging**
